import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'kinyarwanda' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Common
    dashboard: 'Dashboard',
    settings: 'Settings',
    messages: 'Messages',
    notifications: 'Notifications',
    logout: 'Logout',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    submit: 'Submit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    export: 'Export',
    import: 'Import',
    save: 'Save',

    // Language
    language: 'Language',
    english: 'English',
    kinyarwanda: 'Kinyarwanda',
    french: 'Français',
    // Nav
    farmers: 'Farmers',
    veterinarians: 'Veterinarians',
    cahws: 'CAHWs',

    // Farmer
    myCases: 'My Cases',
    healthRecords: 'Health Records',
    myAnimals: 'My Animals',
    activeCases: 'Active Cases',
    resolved: 'Resolved',
    avgResponse: 'Avg Response',
    animals: 'Animals',
    newCase: 'New Case',
    addAnimal: 'Add Animal',
    addRecord: 'Add Record',
    viewDetails: 'View Details',
    reviewCourse: 'Review Course',
    continueLearning: 'Continue Learning',

    // Veterinarian
    cases: 'Cases',
    patients: 'Patients',
    analytics: 'Analytics',
    caseHistory: 'Case History',
    treatmentPlans: 'Treatment Plans',
    scheduleVisit: 'Schedule Visit',
    createPlan: 'Create Treatment Plan',
    treatmentPlanCreated: 'Treatment plan created successfully',
    treatmentDeleted: 'Treatment plan deleted',

    // CAHW
    training: 'Training',
    certifications: 'Certifications',
    community: 'Community',
    progress: 'Progress',
    nearbyCases: 'Nearby Cases',
    nearbyPatients: 'Nearby Patients',
    facilitate: 'Facilitate',

    // Admin
    users: 'Users',
    reports: 'Reports',
    manageUsers: 'Manage Users',
    systemReports: 'System Reports',

    // Dashboard specific
    welcomeBack: 'Welcome back',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    noData: 'No data available',

    // Forms
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    role: 'Role',
    status: 'Status',
    date: 'Date',
    description: 'Description',
    details: 'Details',

    // Farmer Dashboard
    headerSubtitle: "Here's what's happening with your livestock today",
    recentCases: 'Recent Cases',
    viewAllCases: 'View All Cases',
    startAssessment: 'Start Assessment',
    chatWithVet: 'Chat with Vet',
    viewAssessments: 'View Assessments',
    healthAlert: 'Health Alert',
    getHelp: 'Get Help',
    thisMonth: 'This Month',
    casesHandled: 'Cases Handled',
    successRate: 'Success Rate',
    startNewAssessment: 'Start New Assessment',
    animalType: 'Animal Type',
    mainSymptoms: 'Main Symptoms',
    describeSymptoms: 'Describe the symptoms you observed...',
    submitAssessment: 'Submit Assessment',

    // Vet Dashboard
    headerSubtitleVet: 'Manage your cases and track patient outcomes',
    resolvedThisMonth: 'Resolved This Month',
    avgResponseTime: 'Avg Response Time',
    farmersServed: 'Farmers Served',
    searchPlaceholderVet: 'Search by farmer, animal, or case ID...',
    performance: 'Performance',
    resolutionRate: 'Resolution Rate',
    pendingFollowups: 'Pending Follow-ups',
    followupNeeded: 'Follow-up needed today',
    monthlyStats: 'Monthly Stats',
    farmersHelped: 'Farmers Helped',
    animalsTreated: 'Animals Treated',

    // Status
    active: 'Active',
    inactive: 'Inactive',
    pending: 'Pending',
    completed: 'Completed',
    inProgress: 'In Progress',

    cancelled: 'Cancelled',

    // Priorities
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    urgent: 'Urgent',

    // Messages
    noMessages: 'No messages',
    sendMessage: 'Send Message',
    messagesSent: 'Messages Sent',
    messagesReceived: 'Messages Received',

    // Errors
    pleaseLogin: 'Please login to continue',
    unauthorized: 'You are not authorized to access this page',
    notFound: 'Page not found',
    somethingWentWrong: 'Something went wrong',

    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    createAccount: 'Create Account',
    welcomeBackLogin: 'Welcome back to VetLink. Sign in to your account.',
    welcomeBackSignup: 'Join VetLink and connect with veterinary care',
    iAmA: 'I am a',
    noAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    fillAllFields: 'Please fill in all fields',
    passwordsMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    loginFailed: 'Login failed. Please try again.',
    signupFailed: 'Signup failed. Please try again.',
    fullName: 'Full Name',
    agreeTo: 'I agree to the',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    and: 'and',
    getInstantAccess: 'Get instant access to:',
    benefitSupport: 'Real-time veterinary support',
    benefitAssessments: 'Digital health assessments',
    benefitTracking: 'Case tracking and management',

    // Role Descriptions
    roleFarmerDesc: 'Access veterinary care via USSD, mobile app, and web portal',
    roleVetDesc: 'Manage cases and access real-time dashboards',
    roleCAHWDesc: 'Provide first-response care and training',
    roleAdminDesc: 'Manage the entire VetLink platform',

    // Admin Users
    userManagement: 'User Management',
    manageSystemUsers: 'Manage all system users',
    addUser: 'Add User',
    searchUsersPlaceholder: 'Search by name or email...',
    allRoles: 'All',
    joinedDate: 'Joined',
    lockUser: 'Lock',
    unlockUser: 'Unlock',
    deleteUser: 'Delete',

    // Admin Analytics
    systemAnalytics: 'System Analytics',
    monitorPerformance: 'Monitor platform performance and growth metrics',
    growth: 'Growth',
    totalRevenue: 'Total Revenue',
    activeUsers: 'Active Users',
    platformUsage: 'Platform Usage',
    registrations: 'Registrations',
    interactions: 'Interactions',


    // Farmer Content
    farmAnalytics: 'Farm Analytics',
    analyticsSubtitle: 'Track your livestock health trends and performance',
    casesThisMonth: 'Cases This Month',
    successfulTreatments: 'Successful Treatments',
    monthlyCaseTrend: 'Monthly Case Trend',
    caseTypes: 'Case Types',
    topVets: 'Top Veterinarians',
    goodNews: 'Good News',
    recommendation: 'Recommendation',

    // Admin Reports
    generateReport: 'Generate Report',
    reportType: 'Report Type',
    dateRange: 'Date Range',
    exportFormat: 'Export Format',
    downloadReport: 'Download Report',
    customRange: 'Custom Range',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    lastYear: 'Last Year',
    // Farmer NewCase
    reportNewCase: 'Report New Case',
    reportCaseSubtitle: 'Help us assist you by providing details about your animal\'s health issue',
    stepAnimalDetails: 'Animal Details',
    stepIssueDetails: 'Issue Details',
    stepReview: 'Review',
    animalIdName: 'Animal ID / Name',
    animalIdPlaceholder: 'e.g., Cow-001 or Bessie',
    mainIssue: 'Main Issue / Symptoms',
    issuePlaceholder: 'e.g., Reduced milk production, Loss of appetite',
    duration: 'Duration',
    lessThan24h: 'Less than 24 hours',
    oneToThreeDays: '1-3 days',
    threeToSevenDays: '3-7 days',
    moreThanWeek: 'More than a week',
    severity: 'Severity',
    critical: 'Critical',
    detailedDescription: 'Detailed Description',
    describeObservation: 'Describe what you\'ve observed in detail...',
    locationAnimal: 'Location of Animal',
    locationPlaceholder: 'e.g., Pasture A, Pen 3',
    quickResponse: 'Quick Response',
    quickResponseText: 'A veterinarian will review your case and respond within 2-4 hours during business hours.',
    submitCase: 'Submit Case',
    animalTypeSelect: 'Select animal type...',
    selectAnimalType: 'Select animal type...',

    // Animal Types
    dairyCow: 'Dairy Cow',
    beefCattle: 'Beef Cattle',
    goat: 'Goat',
    sheep: 'Sheep',
    pig: 'Pig',
    chicken: 'Chicken',

    // Veterinarian Dashboard
    caseId: 'Case ID',
    farmer: 'Farmer',
    action: 'Action',

    // Veterinarian Analytics
    trackPerformance: 'Track your performance and insights',
    casesResolved: 'Cases Resolved',
    casesOverview: 'Cases Overview',
    casesByType: 'Cases by Type',
    responseTime: 'Response Time',
    under1Hour: 'Under 1 hour',
    oneToFourHours: '1-4 hours',
    fourPlusHours: '4+ hours',
    performanceScore: 'Performance Score',
    excellent: 'Excellent',
    viewRecommendations: 'View Recommendations',
    thisWeek: 'This Week',
    thisQuarter: 'This Quarter',
    thisYear: 'This Year',
    respiratory: 'Respiratory',
    digestive: 'Digestive',
    infections: 'Infections',
    injuries: 'Injuries',

    // Veterinarian Patients
    myPatients: 'My Patients',
    manageFarmers: 'Manage and track farmer accounts',
    searchByNameEmail: 'Search by name, email, or location...',
    lastVisit: 'Last Visit',
    viewProfile: 'View Profile',
    call: 'Call',
    noPatientsFound: 'No patients found',

    // Veterinarian Messages
    typeMessage: 'Type your message...',
    send: 'Send',
    duck: 'Duck',

    // Farmer ViewDetails
    deleteThisCase: 'Delete this Case?',
    deleteCaseConfirmMessage: 'This action cannot be undone. All data associated with this case will be permanently deleted.',
    caseOverview: 'Case Overview',
    symptomsObserved: 'Symptoms Observed',
    animalInformation: 'Animal Information',
    ownerInformation: 'Owner Information',
    treatment: 'Treatment',
    medicines: 'Medicines',
    by: 'by',
    created: 'Created',
    lastUpdated: 'Last Updated',
    share: 'Share',
    overview: 'Overview',
    timeline: 'Timeline',
    animal: 'Animal',

    // Health Records
    pageTitleRecords: 'Health Records',
    pageSubtitleRecords: 'View and manage your animal health history',
    searchPlaceholderRecords: 'Search animal, type, or details...',
    download: 'Download',
    noRecordsFound: 'No records found',
    addRecordModalTitle: 'Add Health Record',
    recordTypeLabel: 'Record Type',
    descriptionLabel: 'Description / Notes',
    saveRecord: 'Save Record',
    enterDetailsPlaceholder: 'Enter procedure details...',
    // Landing Page Redesign
    accessibleHealthcareTitle: 'Accessible Animal Healthcare for Every Farmer',
    accessibleHealthcareDesc: "VetLink connects Rwanda's livestock farmers with veterinary care through the devices they already own—USSD, mobile apps, or web portals.",
    deepSearchPlaceholder: 'Search for vets, health tips, or diseases...',
    ussdNoDataLoader: 'No data? No problem.',
    ussdInteractiveTitle: 'USSD Service (*789#)',
    ussdInteractiveWelcome: 'Welcome to VetLink USSD',
    ussdInteractiveStep1: '1. Report New Case',
    ussdInteractiveStep2: '2. Check Case Status',
    ussdInteractiveStep3: '3. Animal Health Tips',
    ussdInteractiveStep4: '4. My Profile',
    // Landing hero and CTA
    connectedVeterinaryCare: 'Connected Veterinary Care',
    heroLine1: 'Modern Care',
    heroLine2: 'for Every',
    heroLine3: 'Animal',
    heroDesc: "Connect with expert veterinarians, access real-time advice, and manage animal health with Rwanda's most comprehensive veterinary platform.",
    searchPlaceholderLanding: 'Search for veterinarians, treatments, or advice...',
    startFreeTrial: 'Start Free Trial',
    watchDemo: 'Watch Demo',
    hipaaCompliant: 'HIPAA Compliant',
    farmersCountText: '10,000+ Farmers',
    securePlatform: 'Secure Platform',
  },
  kinyarwanda: {
    // Common
    dashboard: 'Ahabanza',
    settings: 'Ibisabwa',
    messages: 'Ubutumwa',
    notifications: 'Menyesha',
    logout: 'Sohoka',
    loading: 'Gihimbazabikoreshwa...',
    error: 'Ikosa',
    success: 'Byagenze neza',
    cancel: 'Emeza',
    submit: 'Ohereza',
    close: 'Funga',
    back: 'Subira inyuma',
    next: 'Komeza',
    previous: 'Ubwacu',
    delete: 'Siba',
    edit: 'Guhindura',
    add: 'Ongeramo',
    search: 'Shakisha',
    filter: 'Gushyira',
    sort: 'Gushyiraho',
    export: 'Gusura hari',
    import: 'Kuramo',
    save: 'Kubika',

    // Language
    language: 'Ururimi',
    english: 'English',
    kinyarwanda: 'Kinyarwanda',
    french: 'Français',
    // Nav
    farmers: 'Aborozi',
    veterinarians: 'Abaveterineri',
    cahws: 'CAHWs',

    // Farmer
    myCases: 'Ibibazo byanjye',
    healthRecords: 'Igitabo cy\'ubuzima',
    myAnimals: 'Inyamabweru zanjye',
    activeCases: 'Ibibazo bikoreshwa',
    resolved: 'Ibyakozwe',
    avgResponse: 'Impinduka y\'igihe',
    animals: 'Inyamabweru',
    newCase: 'Ibibazo Bishya',
    addAnimal: 'Ongeramo Inyamabweru',
    addRecord: 'Ongeramo Icyandetswe',
    viewDetails: 'Reba Amakuru',
    reviewCourse: 'Gerageza Isomo',
    continueLearning: 'Komeza Kwiga',

    // Veterinarian
    cases: 'Ibibazo',
    patients: 'Abafreza',
    analytics: 'Isesengura',
    caseHistory: 'Amateka y\'ibibazo',
    treatmentPlans: 'Gahunda y\'ubuvuzi',

    // CAHW
    training: 'Ikoranabuhanga',
    certifications: 'Iyemeza',
    community: 'Ubwuko',
    progress: 'Aho imbaruko',
    nearbyCases: 'Ibibazo Bihagarara',
    nearbyPatients: 'Abafreza Bihagarara',
    facilitate: 'Singizire',

    // Admin
    users: 'Abakoresha',
    reports: 'Raporo',
    manageUsers: 'Managinga Abakoresha',
    systemReports: 'Raporo z\'Igenamigambi',

    // Dashboard specific
    welcomeBack: 'Murakaza neza',
    quickActions: 'Ibikorwa Byihuse',
    recentActivity: 'Ibikorwa Biheruka',
    viewAll: 'Reba Iyose',
    noData: 'Nta makuru',

    // Forms
    name: 'Izina',
    email: 'Email',
    password: 'Ijambo Ryibanga',
    confirmPassword: 'Emeza Ijambo Ryibanga',
    role: 'Inzira',
    status: 'Imiterere',
    date: 'Itariki',
    description: 'Insobanuro',
    details: 'Amakuru',

    // Farmer Dashboard
    headerSubtitle: 'Ibiri kuba ku matungo yawe uyu munsi',
    recentCases: 'Ibibazo biheruka',
    viewAllCases: 'Reba ibibazo byose',
    startAssessment: 'Tangira isuzuma',
    chatWithVet: 'Vugana na Veterineri',
    viewAssessments: 'Reba amasuzuma',
    healthAlert: 'Integuza y\'ubuzima',
    getHelp: 'Fata ubufasha',
    thisMonth: 'Uku kwezi',
    casesHandled: 'Ibibazo byakemutse',
    successRate: 'Ijanisha ry\'intsinzi',
    startNewAssessment: 'Tangira isuzuma rishya',
    animalType: 'Ubwoko bw\'itungo',
    mainSymptoms: 'Ibimenyetso nyamukuru',
    describeSymptoms: 'Sobanura ibimenyetso wabonye...',
    submitAssessment: 'Ohereza isuzuma',

    // Vet Dashboard & Cases
    headerSubtitleVet: 'Cunga ibibazo byawe kandi usuzume ibisubizo',
    resolvedThisMonth: 'Byakemutse uku kwezi',
    avgResponseTime: 'Impinduka y\'igihe',
    farmersServed: 'Aborozi bafashijwe',
    searchPlaceholderVet: 'Shakisha umworozi, itungo cyangwa numero y\'ikibazo...',
    performance: 'Umusaruro',
    resolutionRate: 'Ikigero cy\'ibyakemutse',
    pendingFollowups: 'Ibigomba gukurikiranwa',
    followupNeeded: 'Bikeneye gukurikiranwa uyu munsi',
    monthlyStats: 'Imibare y\'ukwezi',
    farmersHelped: 'Aborozi bafashijwe',
    animalsTreated: 'Inyamabweru zavuwe',
    caseManagement: 'Gucunga Ibibazo',
    caseManagementSubtitle: 'Kurikirana ibibazo byose by\'aborozi',
    searchPlaceholderCases: 'Shakisha umworozi cyangwa itungo...',
    allCases: 'Ibibazo Byose',
    caseId: 'Numero y\'Ikibazo',
    farmer: 'Umworozi',
    priority: 'Uburemere',
    action: 'Igikorwa',
    createCaseModalTitle: 'Kora Ikibazo Gishya',
    issueSymptoms: 'Ikibazo / Ibimenyetso',
    describeIssuePlaceholder: 'Sobanura ikibazo...',
    location: 'Aho biherereye',
    createCase: 'Kora Ikibazo',

    // Health Records
    pageTitleRecords: 'Igitabo cy\'Ubuzima',
    pageSubtitleRecords: 'Reba kandi ucunge amateka y\'ubuzima bw\'amatungo yawe',
    searchPlaceholderRecords: 'Shakisha itungo, ubwoko cyangwa insobanuro...',
    download: 'Kuramo',
    noRecordsFound: 'Nta byanditswe byabonetse',
    addRecordModalTitle: 'Ongeramo Icyanditswe',
    recordTypeLabel: 'Ubwoko bw\'Icyanditswe',
    descriptionLabel: 'Insobanuro',
    saveRecord: 'Bika Icyanditswe',
    enterDetailsPlaceholder: 'Injiza amakuru ku gikorwa...',

    // Treatment Plans
    managePlansSubtitle: 'Cunga kandi ukurikirane gahunda z\'ubuvuzi',
    activePlans: 'Gahunda zikora',
    avgCompliance: 'Ikigero',
    treatmentRegimen: 'Gahunda y\'imiti',
    additionalNotes: 'Andi mabwiriza',
    startDate: 'Itariki yo gutangira',
    endDate: 'Itariki yo kurangiza',
    durationDays: 'Iminsi',
    createPlan: 'Kora Gahunda',
    newPlan: 'Gahunda Nshya',

    // System Settings
    systemWideSettingsSubtitle: 'Gena imikorere y\'uburyo bwose bwa sisitemu',
    notificationSettings: 'Igenamigambi rya Menyesha',
    securitySettings: 'Umutekano',
    dbBackup: 'Ububiko & Bika',
    systemConfig: 'Igenamigambi rya Sisitemu',
    emailNotifications: 'Kumenyesha kuri Email',
    emailNotificationsDesc: 'Ohereza ubutumwa bwa sisitemu kuri email',
    twoFactorAuth: 'Kugenzura Kabiri',
    twoFactorAuthDesc: 'Gusaba kugenzura kabiri kubayobozi bose',
    sslEncryption: 'Ubwihisho bwa SSL/TLS',
    sslEncryptionDesc: 'Koresha HTTPS kuri byose',
    maxLoginAttempts: 'Umubare ntarengwa wo kwinjira',
    lockAccountDesc: 'Funga konti nyuma yo kugerageza inshuro nyinshi',
    sessionTimeout: 'Igihe cyo guhagarara (iminota)',
    autoLogoutDesc: 'Gusohoka byikora nyuma yo kudatuza',
    autoBackup: 'Kubika byikora',
    autoBackupDesc: 'Emeza kubika ububiko byikora',
    backupFrequency: 'Inshuro z\'ibiko',
    dataRetention: 'Igihe cyo kubika amakuru (iminsi)',
    deleteLogsDesc: 'Siba raporo zarengeje iki gihe',
    maintenanceMode: 'Gukora Isana',
    maintenanceModeDesc: 'Guhagarika by\'agateganyo kwinjira',
    apiAccess: 'Kwinjira kwa API',
    apiAccessDesc: 'Kwemerera izindi porogaramu kwinjira',
    logLevel: 'Urwego rwa Raporo',
    logLevelDesc: 'Urwego rw\'amakuru ya sisitemu',
    unsavedChanges: 'Ufite impinduka zitarikwa. Wibuke kubika mbere yo gusohoka.',
    saveChanges: 'Bika Impinduka',
    enabled: 'Byemejwe',
    disabled: 'Byahagaritswe',
    everyHour: 'Buri saha',
    daily: 'Buri munsi',
    weekly: 'Buri cyumweru',
    monthly: 'Buri kwezi',

    // Status
    active: 'Bikora',
    inactive: 'Ntago bikora',
    pending: 'Biracyakorwa',
    completed: 'Byakozwe',
    inProgress: 'Birigukorwa',

    cancelled: 'Byahagaritswe',

    // Priorities
    high: 'Bihambaye',
    medium: 'Biringaniye',
    low: 'Bike',
    urgent: 'Byihutirwa',
    critical: 'Bikomeye Cyane',

    // Messages
    noMessages: 'Nta butumwa',
    sendMessage: 'Ohereza',
    messagesSent: 'Ubutumwa bwoherejwe',
    messagesReceived: 'Ubutumwa bwakiriwe',
    searchConversations: 'Shakisha ibiganiro...',
    typeMessage: 'Andika ubutumwa...',
    conversations: 'Ibiganiro',

    // Errors
    pleaseLogin: 'Ibuka kwinjira kugira ngo kurikira',
    unauthorized: 'Nta buruhuko bwawe kurambura iyi paje',
    notFound: 'Paje ntiyo hanze',
    somethingWentWrong: 'Habaye ikibazo',

    // Auth
    signIn: 'Injira',
    signUp: 'Iyandikishe',
    createAccount: 'Fungura Konti',
    welcomeBackLogin: 'Murakaza neza kuri VetLink. Injira muri konti yawe.',
    welcomeBackSignup: 'Injira muri VetLink ubone ubuvuzi bw\'amatungo',
    iAmA: 'Ndi',
    noAccount: "Nta konti ufite?",
    alreadyHaveAccount: 'Ufite konti?',
    fillAllFields: 'Uzuza imyanya yose',
    passwordsMismatch: 'Ijambobanga ntirihura',
    passwordTooShort: 'Ijambo ryibanga rigomba kugira inyuguti 6 nibura',
    loginFailed: 'Kwinjira byanze. Ongera ugerageze.',
    signupFailed: 'Kwiyandikisha byanze. Ongera ugerageze.',
    fullName: 'Amazina Yose',
    agreeTo: 'Nemeye',
    termsOfService: 'Amabwiriza y\'Imikoreshereze',
    privacyPolicy: 'Amabwiriza y\'Amakuru Bwite',
    and: 'na',
    getInstantAccess: 'Bona ako kanya:',
    benefitSupport: 'Ubufasha bwa veterineri',
    benefitAssessments: 'Isuzuma ry\'ubuzima',
    benefitTracking: 'Gukurikirana ibibazo',

    // Role Descriptions
    roleFarmerDesc: 'Bona ubuvuzi ukoresheje USSD, porogaramu cyangwa urubuga',
    roleVetDesc: 'Cunga ibibazo kandi urebe imikorere',
    roleCAHWDesc: 'Tanga ubutabazi bw\'ibanze n\'amahugurwa',
    roleAdminDesc: 'Cunga urubuga rwa VetLink rwose',

    // Farmer Content
    farmAnalytics: 'Isesengura',
    analyticsSubtitle: 'Kurikirana ubuzima bw\'amatungo yawe n\'umusaruro',
    casesThisMonth: 'Ibibazo by\'Uku Kwezi',
    successfulTreatments: 'Ubuvuzi Bwatsinze',
    monthlyCaseTrend: 'Imiterere y\'Ibibazo bya Buri Kwezi',
    caseTypes: 'Ubwoko bw\'Ibibazo',
    topVets: 'Abaveterineri Bakomeye',
    goodNews: 'Amakuru Meza',
    recommendation: 'Inama',

    // Add Animal
    addAnimalTitle: 'Ongeramo Itungo Rishya',
    addAnimalSubtitle: 'Andika itungo rishya mu bitabo byawe',
    animalName: 'Izina ry\'Itungo / ID',
    selectType: 'Hitamo ubwoko...',
    dob: 'Itariki y\'Amavuko',
    gender: 'Igitsina',
    male: 'Gabo',
    female: 'Gore',
    weight: 'Ibiro',
    pastHistory: 'Ubuvuzi Buherutse',
    notes: 'Andi Makuru',
    quickTip: 'Inama',
    tipContent: 'Amakuru nyayo y\'itungo afasha abaveterineri gutanga ubuvuzi bwiza.',
    animalAdded: 'Itungo Ryongewe Neza!',
    redirecting: 'Tegereza...',



    // Farmer Animals specific
    openingAddAnimal: 'Gufungura ifishi yo kongeramo itungo',
    searchPlaceholderAnimals: 'Shakisha izina, ubwoko...',
    age: 'Imyaka',
    years: 'imyaka',
    lastCheckup: 'Isuzuma Riheruka',
    viewHealth: 'Reba Ubuzima',
    viewingHealthRecords: 'Kureba ibitabo by\'ubuzima',
    editing: ' guhindura...',
    noAnimalsFound: 'Nta tungo ryabonetse',


    // Farmer Cases specific
    trackManageCases: 'Kurikirana ibibazo byose by\'amatungo yawe',
    openingNewCase: 'Gufungura ifishi y\'ikibazo gishya',
    caseArchived: 'Ikibazo cyabitswe',
    loadingDetails: 'Kureba amakuru ya',
    archive: 'Bika',
    overview: 'Incamake',
    timeline: 'Ingenga Ibihe',
    animal: 'Itungo',

    // Animal Types
    dairyCow: 'Inka y\'Amata',
    beefCattle: 'Inka y\'Inyama',
    goat: 'Ihene',
    sheep: 'Intama',
    pig: 'Ingurube',
    chicken: 'Inkoko',
    duck: 'Imbata',

    // Veterinarian Analytics
    trackPerformance: 'Kurikirana imikorere yawe n\'amakuru',
    casesResolved: 'Ibibazo Byakemutse',
    casesOverview: 'Incamake y\'Ibibazo',
    casesByType: 'Ibibazo ku bwoko',
    responseTime: 'Igihe cyo Gusubiza',
    under1Hour: 'Munsi y\'isaha imwe',
    oneToFourHours: 'Amasaha 1-4',
    fourPlusHours: 'Amasaha 4+',
    performanceScore: 'Amanota y\'Imikorere',
    excellent: 'Byiza cyane',
    viewRecommendations: 'Reba Inama',
    thisWeek: 'Iki Cyumweru',
    thisQuarter: 'Iki Gihembwe',
    thisYear: 'Iki Mwaka',
    respiratory: 'Ubuhumekero',
    digestive: 'Imigendekere',
    infections: 'Indwara',
    injuries: 'Ibikomere',

    // Veterinarian Patients
    myPatients: 'Abarwayi Banjye',
    manageFarmers: 'Gucunga no gukurikirana konti z\'aborozi',
    searchByNameEmail: 'Shakisha ku izina, imeri, cyangwa ahantu...',
    lastVisit: 'Isura Riheruka',
    viewProfile: 'Reba Umwirondoro',
    call: 'Hamagara',
    noPatientsFound: 'Nta barwayi babonetse',

    // Farmer NewCase
    reportNewCase: 'Raporo Ikibazo Gishya',
    reportCaseSubtitle: 'Dufashe kugufasha utanga ibisobanuro ku kibazo cy\'ubuzima bw\'itungo ryawe',
    stepAnimalDetails: 'Amakuru y\'Itungo',
    stepIssueDetails: 'Amakuru y\'Ikibazo',
    stepReview: 'Suzuma',
    animalIdName: 'ID / Izina ry\'Itungo',
    animalIdPlaceholder: 'urugero, Cow-001 cyangwa Bessie',
    mainIssue: 'Ikibazo Nyamukuru / Ibimenyetso',
    issuePlaceholder: 'urugero, Kugabanuka kw\'amata, Kubura ubushake bwo kurya',
    duration: 'Igihe Bimaze',
    quickResponseText: 'Umuganga w\'amatungo arasuzuma ikibazo cyawe asubize mu masaha 2-4 mu gihe cy\'akazi.',
    submitCase: 'Ohereza Ikibazo',
    animalTypeSelect: 'Hitamo ubwoko bw\'itungo...',

    // Farmer ViewDetails
    deleteThisCase: 'Siba Iki Kibazo?',
    deleteCaseConfirmMessage: 'Iki gikorwa ntikigarurwa. Amakuru yose ajyanye nabyo arahanagurwa burundu.',
    caseOverview: 'Incamake y\'Ikibazo',
    symptomsObserved: 'Ibimenyetso Byagaragaye',
    animalInformation: 'Amakuru y\'Itungo',
    ownerInformation: 'Amakuru ya Nyiraryo',
    treatment: 'Ubuvuzi',
    medicines: 'Imiti',
    by: 'na',
    created: 'Cyakozwe',
    lastUpdated: 'Giheruka Kuvugururwa',
    share: 'Sangiza',

    // Admin Users
    userManagement: 'Gucunga Abakoresha',
    manageSystemUsers: 'Genzura abakoresha bose ba sisitemu',
    addUser: 'Ongeramo Umukoresha',
    searchUsersPlaceholder: 'Shakisha izina cyangwa email...',
    allRoles: 'Byose',
    joinedDate: 'Yiyandikishije',
    lockUser: 'Funga',
    unlockUser: 'Fungura',
    deleteUser: 'Siba',

    // Admin Analytics
    systemAnalytics: 'Isesengura rya Sisitemu',
    monitorPerformance: 'Kurikirana imikorere ya sisitemu n\'iterambere',
    growth: 'Iterambere',
    totalRevenue: 'Amafaranga Yinjijwe',
    activeUsers: 'Abakoresha Bakora',
    platformUsage: 'Imikoreshereze y\'Urubuga',
    registrations: 'Iyandikisha',
    interactions: 'Ibikorwa',

    // Admin Reports
    generateReport: 'Kora Raporo',
    reportType: 'Ubwoko bwa Raporo',
    dateRange: 'Igihe',
    exportFormat: 'Imiterere y\'Iyohereza',
    downloadReport: 'Kuramo Raporo',
    customRange: 'Igihe Cyahisemo',
    last7Days: 'Iminsi 7 Ishize',
    last30Days: 'Iminsi 30 Ishize',
    lastYear: 'Umwaka Ushize',
    // Landing Page Redesign
    accessibleHealthcareTitle: 'Ubuvuzi bw\'Amatungo kuri Buri Mworozi',
    accessibleHealthcareDesc: "VetLink ihuza aborozi b'amatungo mu Rwanda n'ubuvuzi bwa veterineri binyuze mu bikoresho basanzwe bafite—USSD, porogaramu zigendanwa, cyangwa imbuga za internet.",
    deepSearchPlaceholder: 'Shakisha abaveterineri, inama z\'ubuzima, cyangwa indwara...',
    ussdNoDataLoader: 'Nta bumenyi? Nta kibazo.',
    ussdInteractiveTitle: 'Serivisi ya USSD (*789#)',
    ussdInteractiveWelcome: 'Murakaza neza kuri VetLink USSD',
    ussdInteractiveStep1: '1. Raporo Ikibazo Gishya',
    ussdInteractiveStep2: '2. Reba Imiterere y\'Ikibazo',
    ussdInteractiveStep3: '3. Inama ku Buzima bw\'Amatungo',
    ussdInteractiveStep4: '4. Umwirondoro Wanjye',
    // Landing hero and CTA
    connectedVeterinaryCare: 'Ubuvuzi bw\'amatungo buhuza abantu',
    heroLine1: 'Ubuvuzi Bigezweho',
    heroLine2: 'kuri Buri',
    heroLine3: 'Igitungo',
    heroDesc: 'Vugana n\'abaveterineri b\'inararibonye, ubone inama z\'ako kanya, kandi ucunge ubuzima bw\'amatungo ukoresheje urubuga rwa VetLink.',
    searchPlaceholderLanding: 'Shakisha abaveterineri, imiti, cyangwa inama...',
    startFreeTrial: 'Tangiza Ikizamini Ku Buntu',
    watchDemo: 'Reba Demo',
    hipaaCompliant: 'Bikurikije amategeko y\'umutekano',
    farmersCountText: 'Aborozi 10,000+',
    securePlatform: 'Urubuga Rwizewe',
  },
  fr: {
    // Common
    dashboard: 'Tableau de Bord',
    settings: 'Paramètres',
    messages: 'Messages',
    notifications: 'Notifications',
    logout: 'Déconnexion',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    cancel: 'Annuler',
    submit: 'Soumettre',
    close: 'Fermer',
    back: 'Retour',
    next: 'Suivant',
    previous: 'Précédent',
    delete: 'Supprimer',
    edit: 'Modifier',
    add: 'Ajouter',
    search: 'Rechercher',
    filter: 'Filtrer',
    sort: 'Trier',
    export: 'Exporter',
    import: 'Importer',
    save: 'Enregistrer',

    // Language
    language: 'Langue',
    english: 'English',
    kinyarwanda: 'Kinyarwanda',
    french: 'Français',
    // Nav
    farmers: 'Éleveurs',
    veterinarians: 'Vétérinaires',
    cahws: 'CAHWs',

    // Farmer
    myCases: 'Mes Cas',
    healthRecords: 'Dossiers de Santé',
    myAnimals: 'Mes Animaux',
    activeCases: 'Cas Actifs',
    resolved: 'Résolus',
    avgResponse: 'Réponse Moyenne',
    animals: 'Animaux',
    newCase: 'Nouveau Cas',
    addAnimal: 'Ajouter un Animal',
    addRecord: 'Ajouter un Dossier',
    viewDetails: 'Voir les Détails',
    reviewCourse: 'Examiner le Cours',
    continueLearning: 'Continuer l\'Apprentissage',

    // Veterinarian
    cases: 'Cas',
    patients: 'Patients',
    analytics: 'Analyse',
    caseHistory: 'Historique des Cas',
    treatmentPlans: 'Plans de Traitement',

    // CAHW
    training: 'Formation',
    certifications: 'Certifications',
    community: 'Communauté',
    progress: 'Progrès',
    nearbyCases: 'Cas à Proximité',
    nearbyPatients: 'Patients à Proximité',
    facilitate: 'Faciliter',

    // Admin
    users: 'Utilisateurs',
    reports: 'Rapports',
    manageUsers: 'Gérer les Utilisateurs',
    systemReports: 'Rapports Système',

    // Dashboard specific
    welcomeBack: 'Bienvenue',
    quickActions: 'Actions Rapides',
    recentActivity: 'Activité Récente',
    viewAll: 'Voir Tout',
    noData: 'Aucune donnée disponible',

    // Forms
    name: 'Nom',
    email: 'Email',
    password: 'Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    role: 'Rôle',
    status: 'Statut',
    date: 'Date',
    description: 'Description',
    details: 'Détails',

    // Farmer Dashboard
    headerSubtitle: 'Voici ce qui se passe avec votre bétail aujourd\'hui',
    recentCases: 'Cas Récents',
    viewAllCases: 'Voir Tous les Cas',
    startAssessment: 'Commencer l\'Évaluation',
    chatWithVet: 'Discuter avec le Vétérinaire',
    viewAssessments: 'Voir les Évaluations',
    healthAlert: 'Alerte Santé',
    getHelp: 'Obtenir de l\'Aide',
    thisMonth: 'Ce Mois-ci',
    casesHandled: 'Cas Traités',
    successRate: 'Taux de Succès',
    startNewAssessment: 'Commencer une Nouvelle Évaluation',
    animalType: 'Type d\'Animal',
    mainSymptoms: 'Symptômes Principaux',
    describeSymptoms: 'Décrivez les symptômes observés...',
    submitAssessment: 'Soumettre l\'Évaluation',

    // Vet Dashboard & Cases
    headerSubtitleVet: 'Gérez vos cas et suivez les résultats des patients',
    resolvedThisMonth: 'Résolus Ce Mois-ci',
    avgResponseTime: 'Temps de Réponse Moyen',
    farmersServed: 'Éleveurs Servis',
    searchPlaceholderVet: 'Rechercher par éleveur, animal ou ID de cas...',
    performance: 'Performance',
    resolutionRate: 'Taux de Résolution',
    pendingFollowups: 'Suivis En Attente',
    followupNeeded: 'Suivi nécessaire aujourd\'hui',
    monthlyStats: 'Statistiques Mensuelles',
    farmersHelped: 'Éleveurs Aidés',
    animalsTreated: 'Animaux Traités',
    caseManagement: 'Gestion des Cas',
    caseManagementSubtitle: 'Suivre et gérer tous les cas d\'éleveurs',
    searchPlaceholderCases: 'Rechercher par éleveur ou animal...',
    allCases: 'Tous les Cas',
    caseId: 'ID du Cas',
    farmer: 'Éleveur',
    priority: 'Priorité',
    action: 'Action',
    createCaseModalTitle: 'Créer un Nouveau Cas',
    issueSymptoms: 'Problème / Symptômes',
    describeIssuePlaceholder: 'Décrivez le problème...',
    location: 'Lieu',
    createCase: 'Créer le Cas',

    // Health Records
    pageTitleRecords: 'Dossiers de Santé',
    pageSubtitleRecords: 'Voir et gérer l\'historique de santé de vos animaux',
    searchPlaceholderRecords: 'Rechercher par animal, type ou description...',
    download: 'Télécharger',
    noRecordsFound: 'Aucun dossier trouvé',
    addRecordModalTitle: 'Ajouter un Dossier de Santé',
    recordTypeLabel: 'Type de Dossier',
    descriptionLabel: 'Description / Notes',
    saveRecord: 'Enregistrer le Dossier',
    enterDetailsPlaceholder: 'Entrez les détails de la procédure...',

    // Treatment Plans
    managePlansSubtitle: 'Gérer et surveiller les plans de traitement des patients',
    activePlans: 'Plans Actifs',
    avgCompliance: 'Conformité Moyenne',
    treatmentRegimen: 'Régime de Traitement',
    additionalNotes: 'Notes Supplémentaires',
    startDate: 'Date de Début',
    endDate: 'Date de Fin',
    durationDays: 'Durée (Jours)',
    createPlan: 'Créer le Plan',
    newPlan: 'Nouveau Plan',

    // System Settings
    systemWideSettingsSubtitle: 'Configurer les paramètres système et de sécurité',
    notificationSettings: 'Paramètres de Notification',
    securitySettings: 'Paramètres de Sécurité',
    dbBackup: 'Base de Données et Sauvegarde',
    systemConfig: 'Configuration Système',
    emailNotifications: 'Notifications Email',
    emailNotificationsDesc: 'Envoyer des alertes système par email',
    twoFactorAuth: 'Authentification à Deux Facteurs',
    twoFactorAuthDesc: 'Exiger la 2FA pour tous les administrateurs',
    sslEncryption: 'Chiffrement SSL/TLS',
    sslEncryptionDesc: 'Utiliser HTTPS pour toutes les connexions',
    maxLoginAttempts: 'Tentatives de Connexion Max',
    lockAccountDesc: 'Verrouiller le compte après ce nombre d\'échecs',
    sessionTimeout: 'Délai d\'Expiration de Session (minutes)',
    autoLogoutDesc: 'Déconnexion automatique après inactivité',
    autoBackup: 'Sauvegarde Automatique',
    autoBackupDesc: 'Activer les sauvegardes automatiques',
    backupFrequency: 'Fréquence de Sauvegarde',
    dataRetention: 'Période de Rétention des Données (jours)',
    deleteLogsDesc: 'Supprimer les journaux plus anciens que cette période',
    maintenanceMode: 'Mode Maintenance',
    maintenanceModeDesc: 'Désactiver temporairement l\'accès aux utilisateurs',
    apiAccess: 'Accès API',
    apiAccessDesc: 'Autoriser les intégrations API externes',
    logLevel: 'Niveau de Journalisation',
    logLevelDesc: 'Niveau de détail des journaux système',
    unsavedChanges: 'Vous avez des modifications non enregistrées. N\'oubliez pas de sauvegarder avant de quitter.',
    saveChanges: 'Enregistrer les Modifications',
    enabled: 'Activé',
    disabled: 'Désactivé',
    everyHour: 'Chaque Heure',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',

    // Status
    active: 'Actif',
    inactive: 'Inactif',
    pending: 'En Attente',
    completed: 'Complété',
    inProgress: 'En Cours',

    cancelled: 'Annulé',

    // Priorities
    high: 'Élevée',
    medium: 'Moyenne',
    low: 'Basse',
    urgent: 'Urgent',

    // Messages
    noMessages: 'Aucun message',
    sendMessage: 'Envoyer un Message',
    messagesSent: 'Messages Envoyés',
    messagesReceived: 'Messages Reçus',

    // Errors
    pleaseLogin: 'Veuillez vous connecter pour continuer',
    unauthorized: 'Vous n\'êtes pas autorisé à accéder à cette page',
    notFound: 'Page non trouvée',
    somethingWentWrong: 'Quelque chose s\'est mal passé',

    // Auth
    signIn: 'Se Connecter',
    signUp: 'S\'inscrire',
    createAccount: 'Créer un Compte',
    welcomeBackLogin: 'Bienvenue sur VetLink. Connectez-vous à votre compte.',
    welcomeBackSignup: 'Rejoignez VetLink et connectez-vous aux soins vétérinaires',
    iAmA: 'Je suis un',
    noAccount: "Vous n'avez pas de compte ?",
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    fillAllFields: 'Veuillez remplir tous les champs',
    passwordsMismatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Le mot de passe doit contenir au moins 6 caractères',
    loginFailed: 'Échec de la connexion. Veuillez réessayer.',
    signupFailed: 'Échec de l\'inscription. Veuillez réessayer.',
    fullName: 'Nom Complet',
    agreeTo: 'J\'accepte les',
    termsOfService: 'Conditions d\'Utilisation',
    privacyPolicy: 'Politique de Confidentialité',
    and: 'et',
    getInstantAccess: 'Obtenez un accès instantané à :',
    benefitSupport: 'Support vétérinaire en temps réel',
    benefitAssessments: 'Évaluations de santé numériques',
    benefitTracking: 'Suivi et gestion des cas',

    // Role Descriptions
    roleFarmerDesc: 'Accédez aux soins vétérinaires via USSD, application mobile et portail web',
    roleVetDesc: 'Gérer les cas et accéder aux tableaux de bord en temps réel',
    roleCAHWDesc: 'Fournir les premiers soins et la formation',
    roleAdminDesc: 'Gérer l\'ensemble de la plateforme VetLink',

    // Farmer Content
    farmAnalytics: 'Analyses de la Ferme',
    analyticsSubtitle: 'Suivez les tendances de santé et les performances de votre bétail',
    casesThisMonth: 'Cas Ce Mois-ci',
    successfulTreatments: 'Traitements Réussis',
    monthlyCaseTrend: 'Tendance Mensuelle des Cas',
    caseTypes: 'Types de Cas',
    topVets: 'Meilleurs Vétérinaires',
    goodNews: 'Bonne Nouvelle',
    recommendation: 'Recommandation',

    // Add Animal
    addAnimalTitle: 'Ajouter un Nouvel Animal',
    addAnimalSubtitle: 'Enregistrer un nouvel animal dans votre inventaire',
    animalName: 'Nom / ID de l\'Animal',
    selectType: 'Sélectionner le type...',
    dob: 'Date de Naissance',
    gender: 'Sexe',
    male: 'Mâle',
    female: 'Femelle',
    weight: 'Poids',
    pastHistory: 'Antécédents Médicaux',
    notes: 'Notes Supplémentaires',
    quickTip: 'Conseil Rapide',
    tipContent: 'Des informations précises aident les vétérinaires à fournir de meilleurs soins.',
    animalAdded: 'Animal Ajouté avec Succès !',
    redirecting: 'Redirection...',
    searchConversations: 'Rechercher des conversations...',
    typeMessage: 'Tapez votre message...',
    conversations: 'Conversations',

    // Farmer Animals specific
    openingAddAnimal: 'Ouverture du formulaire d\'ajout d\'animal',
    searchPlaceholderAnimals: 'Rechercher par nom, type ou race...',
    age: 'Âge',
    years: 'ans',
    lastCheckup: 'Dernier Contrôle',
    viewHealth: 'Voir la Santé',
    viewingHealthRecords: 'Affichage des dossiers de santé',
    editing: 'Édition',
    noAnimalsFound: 'Aucun animal trouvé',

    // Farmer Cases specific
    trackManageCases: 'Suivre et gérer tous les cas de santé de votre bétail',
    openingNewCase: 'Ouverture du formulaire de nouveau cas',
    caseArchived: 'Cas archivé',
    loadingDetails: 'Chargement des détails pour',
    archive: 'Archiver',

    // Veterinarian Analytics
    trackPerformance: 'Suivez vos performances et vos insights',
    casesResolved: 'Cas Résolus',
    casesOverview: 'Aperçu des Cas',
    casesByType: 'Cas par Type',
    responseTime: 'Temps de Réponse',
    under1Hour: "Moins d'1 heure",
    oneToFourHours: '1-4 heures',
    fourPlusHours: '4+ heures',
    performanceScore: 'Score de Performance',
    excellent: 'Excellent',
    viewRecommendations: 'Voir les Recommandations',
    thisWeek: 'Cette Semaine',
    thisQuarter: 'Ce Trimestre',
    thisYear: 'Cette Année',
    respiratory: 'Respiratoire',
    digestive: 'Digestif',
    infections: 'Infections',
    injuries: 'Blessures',

    // Veterinarian Patients
    myPatients: 'Mes Patients',
    manageFarmers: 'Gérer et suivre les comptes des agriculteurs',
    searchByNameEmail: 'Rechercher par nom, email ou emplacement...',
    lastVisit: 'Dernière Visite',
    viewProfile: 'Voir le Profil',
    call: 'Appeler',
    noPatientsFound: 'Aucun patient trouvé',

    // Farmer NewCase
    reportNewCase: 'Signaler un Nouveau Cas',
    reportCaseSubtitle: 'Aidez-nous à vous assister en fournissant des détails sur le problème de santé de votre animal',
    stepAnimalDetails: 'Détails de l\'Animal',
    stepIssueDetails: 'Détails du Problème',
    stepReview: 'Revue',
    animalIdName: 'ID / Nom de l\'Animal',
    animalIdPlaceholder: 'ex., Cow-001 ou Bessie',
    mainIssue: 'Problème Principal / Symptômes',
    issuePlaceholder: 'ex., Réduction de la production de lait, Perte d\'appétit',
    duration: 'Durée',
    lessThan24h: 'Moins de 24 heures',
    oneToThreeDays: '1-3 jours',
    threeToSevenDays: '3-7 jours',
    moreThanWeek: 'Plus d\'une semaine',
    severity: 'Gravité',
    critical: 'Critique',
    detailedDescription: 'Description Détaillée',
    describeObservation: 'Décrivez ce que vous avez observé en détail...',
    locationAnimal: 'Emplacement de l\'Animal',
    locationPlaceholder: 'ex., Pâturage A, Enclos 3',
    quickResponse: 'Réponse Rapide',
    quickResponseText: 'Un vétérinaire examinera votre cas et répondra dans les 2-4 heures pendant les heures ouvrables.',
    submitCase: 'Soumettre le Cas',
    animalTypeSelect: 'Sélectionnez le type d\'animal...',

    // Farmer ViewDetails
    deleteThisCase: 'Supprimer ce Cas ?',
    deleteCaseConfirmMessage: 'Cette action est irréversible. Toutes les données associées seront définitivement supprimées.',
    caseOverview: 'Aperçu du Cas',
    symptomsObserved: 'Symptômes Observés',
    animalInformation: 'Informations sur l\'Animal',
    ownerInformation: 'Informations sur le Propriétaire',
    treatment: 'Traitement',
    medicines: 'Médicaments',
    by: 'par',
    created: 'Créé le',
    lastUpdated: 'Dernière Mise à Jour',
    share: 'Partager',
    lockUser: 'Verrouiller',
    unlockUser: 'Déverrouiller',
    deleteUser: 'Supprimer',

    // Admin Analytics
    systemAnalytics: 'Analyse du Système',
    monitorPerformance: 'Surveiller les performances de la plateforme et les mesures de croissance',
    growth: 'Croissance',
    totalRevenue: 'Revenu Total',
    activeUsers: 'Utilisateurs Actifs',
    platformUsage: 'Utilisation de la Plateforme',
    registrations: 'Inscriptions',
    interactions: 'Interactions',

    // Admin Reports
    generateReport: 'Générer un Rapport',
    reportType: 'Type de Rapport',
    dateRange: 'Plage de Dates',
    exportFormat: 'Format d\'Exportation',
    downloadReport: 'Télécharger le Rapport',
    customRange: 'Plage Personnalisée',
    last7Days: '7 Derniers Jours',
    last30Days: '30 Derniers Jours',
    lastYear: 'L\'Année Dernière',
    overview: 'Aperçu',
    timeline: 'Chronologie',
    animal: 'Animal',

    // Animal Types
    dairyCow: 'Vache Laitière',
    beefCattle: 'Bœuf',
    goat: 'Chèvre',
    sheep: 'Mouton',
    pig: 'Cochon',
    chicken: 'Poulet',
    duck: 'Canard',
    // Landing Page Redesign
    accessibleHealthcareTitle: 'Des Soins Vétérinaires Accessibles pour Chaque Éleveur',
    accessibleHealthcareDesc: "VetLink connecte les éleveurs de bétail du Rwanda aux soins vétérinaires via les appareils qu'ils possèdent déjà—USSD, applications mobiles ou portails web.",
    deepSearchPlaceholder: 'Rechercher des vétérinaires, des conseils de santé ou des maladies...',
    ussdNoDataLoader: 'Pas de données ? Pas de problème.',
    ussdInteractiveTitle: 'Service USSD (*789#)',
    ussdInteractiveWelcome: 'Bienvenue sur VetLink USSD',
    ussdInteractiveStep1: '1. Signaler un Nouveau Cas',
    ussdInteractiveStep2: '2. Vérifier l\'État du Cas',
    ussdInteractiveStep3: '3. Conseils de Santé Animale',
    ussdInteractiveStep4: '4. Mon Profil',
    // Landing hero and CTA
    connectedVeterinaryCare: 'Soins Vétérinaires Connectés',
    heroLine1: 'Soins Modernes',
    heroLine2: 'pour Chaque',
    heroLine3: 'Animal',
    heroDesc: "Connectez-vous avec des vétérinaires experts, accédez à des conseils en temps réel et gérez la santé des animaux avec la plateforme vétérinaire la plus complète du Rwanda.",
    searchPlaceholderLanding: 'Rechercher des vétérinaires, des traitements ou des conseils...',
    startFreeTrial: 'Commencer l\'essai gratuit',
    watchDemo: 'Voir la démo',
    hipaaCompliant: 'Conforme HIPAA',
    farmersCountText: '10 000+ Éleveurs',
    securePlatform: 'Plateforme Sécurisée',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const storedLanguage = localStorage.getItem('vetlink_language') as Language;
    if (storedLanguage && ['en', 'kinyarwanda', 'fr'].includes(storedLanguage)) {
      setLanguageState(storedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('vetlink_language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
